TRAEFIK_BRIDGE ?= traefiknet
USER_UID ?= $(shell id -ur)
USER_GID ?= $(shell id -gr)
NAME ?= wiki
HOSTNAME ?= $(NAME).docker.localhost
MYSQL_IMAGE ?= amery/docker-alpine-mariadb
MYSQL_DATABASE ?= wiki
MYSQL_USER ?= $(MYSQL_DATABASE)
MYSQL_PASSWORD ?= user_password
MYSQL_ROOT_PASSWORD ?= root_password
NGINX_IMAGE ?= amery/docker-alpine-nginx
PHP_IMAGE ?= amery/docker-alpine-php7
WIKI_ADMIN ?= Admin
WIKI_ADMIN_PASSWORD ?= admin_password
WIKI_NAME ?= My Mediawiki
WIKI_URL ?= https://$(HOSTNAME)
